### ISSUE TITLE
performance/caching/response  "Response Caching"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1679]
- [x] Update ResponseCaching docs  #1969 
- [x] graphic needs to be updated to include the caching done by the middleware on the server
- [ ] Add fiddler image of cache header
- [ ] See [this SO thread](http://stackoverflow.com/questions/40369112) When updating doc, use fiddler to show how it works.
- [ ] UE Edit
- [ ] line numbers off
- [ ] DISQUS 
- [x] Update to RTM
- [ ] Document cache tag helper in response caching doc  #1948 
- [ ] Add response caching middleware content to the response caching doc  #1947 
- [ ] #1969  update to reflect the addition of the VaryByQueryKey property that was added in https://github.com/aspnet/Mvc/pull/5383 and the addition of the response caching middleware on the server.
