### ISSUE TITLE
fundamentals/environments.md "Working with Multiple Environments"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2028]
- [x] #2012 case sensitivity 
- [x] #2030 add the ability to set [environment variables on IIS worker processes](https://www.iis.net/configreference/system.applicationhost/applicationpools/add/environmentvariables) was  IIS 10.
- [x] UE Edit
- [x]  #2029 publish my app using all those 3 different predefined environment variables  
- [x] See if [this SO post](http://stackoverflow.com/questions/31049152/publish-to-iis-setting-environment-variable/37455594#37455594) applies

**Comment by Rick-Anderson** [comment]
per customer
>Working on Linux here and trying to run in a Development environment because "dotnet run" defaults to Production. The docs suggests to set the variable Hosting__Environment, e.g.: "export Hosting__Environment=Development". This does not work, instead use "export ASPNETCORE_ENVIRONMENT=Development" and you'll be happy coding

**Comment by Rick-Anderson** [comment]
per DISQUS customer:
> After modifying the ASPNET_ENV (orHosting:Environment) variable in the web profile to be set to Staging, the launchSettings.json file in our sample project is shown below...

It took a while for me to figure out I had to change the profile selection at the top, perhaps a screengrab of that that with the dropdown for Profile highlighted would help, e.g.:
![original 1](https://cloud.githubusercontent.com/assets/3605364/19841695/8018f65e-9eb3-11e6-9778-5c7c0320af16.jpg)
