### ISSUE TITLE
Issues before we can go live with DocFX/OPS

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2057]
- [x] Replace API links with type name #2079 @v-anpasi ETA:
- [x] Fix download links  #2093 @v-anpasi fix by https://github.com/aspnet/Docs/pull/2116
- [x] Fix API link on TOC  #2054   @bradygaster 
- [x] remove hex char from metadata  #2051 fixed by #2073
- [x] ASP.NET hub page needs link to ASP.NET Core #2055 
- [x] Update content on hub page  #2056   @tdykstra ETA:
- [x] Update content on on [intro page](https://review.docs.microsoft.com/en-us/aspnet/core/)  @RickAndMSFT PR #2096 fixes this.
- [x] Update WebHooks page #2062 fixed with #2082

**Good to fix but not show stoppers:**

- [ ] Update link on docs.microsoft.com #2069  @bradygaster ETA: Nov 12
- [x] #2063 add links to EF Core and .NET Core 
- [x]  Fix DocFX builds so TOC works correctly #2064  fixed by #2117 
- [x] Fix DocFX warnings #2107 @RickAndMSFT ETA: Nov 6
- [x]  Update style guide  #2094  @tdykstra ETA: Nov 4

**Post conversion:** 

- [ ] Verify all static links  #2059  @tdykstra 
- [x] Update Intro page #2065  @tdykstra 
- [x] Enable Travis and AppVeyor for external PR's #2067   @spboyer 
- [ ] replace complicated relative links with xref links #2047
