### ISSUE TITLE
Update the remaining docs that haven't been updated for RTM

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#2259]
- [x] [Fundamentals/Application startup](
https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/startup.md) tdykstra #2270 
- [x] [Fundamentals/Error Handling](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/error-handling.md) tdykstra 
- [x] [Fundamentals/Managing application state](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/app-state.md) #858 Rick-Anderson
- [x] fundamentals/localization Rick-Anderson
- [x] [View components](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/view-components.md) Rick-Anderson
- [x] [MVC/Views/Working with forms](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/working-with-forms.md)   #1366 Rick-Anderson
- [x] [Testing/Integration Testing](https://github.com/aspnet/Docs/blob/master/aspnetcore/testing/integration-testing.md) tdykstra 
- [ ] [Client-side/Using Angular for Single Page Applications](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/angular.md) spboyer
- [ ] [Client-side/Bundling and Minification](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md ) spboyer #1786 
- [x] [Security/Authentication/Account Confirmation and Password Recovery](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/accconfirm.md) Rick-Anderson
- [x] [Security/Authentication/Two-factor authentication with SMS](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/2fa.md) Rick-Anderson
- [x] [Performance/In Memory Caching](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/memory.md) Rick-Anderson PR #2324
- [x] [Migration/Migrating HTTP Modules to Middleware](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/http-modules.md) tdykstra #2331

**Comment by Rick-Anderson** [comment]
@spboyer you've been assigned
- [ ] [Client-side/Using Angular for Single Page Applications](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/angular.md) spboyer

**Comment by spboyer** [comment]
@SteveSandersonMS - do you think that we should be documenting JavaScriptServices on [Client-side/Using Angular for Single Page Applications](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/angular.md) or do we wait for the new templates?

**Comment by Rick-Anderson** [comment]
Closing master issue.
