### ISSUE TITLE
fundamentals/configuration "Configuration" command line providers & inject Options

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2409]
- [ ] Configuration: Document format supported for command line arguments provider #1382
- [x] Markup to show how to inject Options in Configuration document #437
- [x] Address MVP summit feedback on Configuration #2408

**Comment by guardrex** [comment]
@Rick-Anderson Your 2nd checkbox for #437 is covered by #4214.

**Comment by scottaddie** [comment]
@guardrex Thanks for letting me know. I updated the checkbox.
