### ISSUE TITLE
aspnet/core/fundamentals/logging "Introduction to Logging in ASP.NET Core"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3412]
- [x] Incorporate 2.0 changes -- see #3388
  - [x] https://stackoverflow.com/questions/45214468/asp-net-core-2-0-appsettings-development-json-not-working-with-logging-configura
  - [x] https://stackoverflow.com/questions/45085682/asp-net-core-2-0-and-logging
- [x] #1171 Document why we have no LogAsync methods
- [x] ~~This example~~ Preceding example - but remove code in sentence.
- [x]  consider removing log category/level and pointing to logger document
- [x]  Debug output has too much other info  - point that out.
- [x] ~~Make a doc for the LoggerMessage.DefineScope pattern #2810~~ separate doc
- [x] LF comment: "What do you recommend to use for log filtering? appsettings.json or withFilter." --provide guidance
- [x] LF comment - the naming convention for constants in c# is pascal case whereas in the LoggingEvents, the variables defined are all uppercase with underscore -- fix code in sample
- [x] LF comment - add JSNLog as one of the third-party logging providers
- [x] xsp thread - on Linux is it default behavior to write logs to /var/log/message

Fixes #1171
