### ISSUE TITLE
WIP tracking of updating ASP.NET Classic doc pages to use Visual Studio  VS 2017

### ISSUE THREAD

**Issue by eriawan** [aspnet/Docs#3474]
This issue is an umbrella task to update some doc pages to use VS 2017, whereas applicable (not all pages needs to be updated to have VS 2017).
The related accepted proposal for this is issue #3452.
The pages that needs updates are: 

- [x] [https://github.com/aspnet/Docs/blob/master/aspnet/web-api/overview/getting-started-with-aspnet-web-api/tutorial-your-first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnet/web-api/overview/getting-started-with-aspnet-web-api/tutorial-your-first-web-api.md) Related PR: #3808 (STATUS: PR submitted, ~~waiting for review~~, MERGED] 
- [x] Under [Testing and Debugging](https://docs.microsoft.com/en-us/aspnet/web-api/overview/testing-and-debugging/) section, [https://github.com/aspnet/Docs/blob/master/aspnet/web-api/overview/testing-and-debugging/tracing-in-aspnet-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnet/web-api/overview/testing-and-debugging/tracing-in-aspnet-web-api.md) Related PR: #4050 (STATUS: PR submitted, ~~waiting for review~~, MERGED]
- [x] [https://github.com/aspnet/Docs/blob/master/aspnet/web-api/overview/testing-and-debugging/unit-testing-with-aspnet-web-api.md] (https://github.com/aspnet/Docs/blob/master/aspnet/web-api/overview/testing-and-debugging/unit-testing-with-aspnet-web-api.md) Related PR: #4308 (STATUS: PR submitted, ~~waiting for review~~,MERGED)
- [x] [https://github.com/aspnet/Docs/blob/master/aspnet/web-api/overview/testing-and-debugging/unit-testing-controllers-in-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnet/web-api/overview/testing-and-debugging/unit-testing-controllers-in-web-api.md) Related PR: #4308 (STATUS: PR submitted, ~~waiting for review~~, MERGED)
- [x] [https://docs.microsoft.com/en-us/aspnet/web-api/overview/testing-and-debugging/mocking-entity-framework-when-unit-testing-aspnet-web-api-2](https://docs.microsoft.com/en-us/aspnet/web-api/overview/testing-and-debugging/mocking-entity-framework-when-unit-testing-aspnet-web-api-2) Related PR: #4308 (STATUS: PR submitted, ~~waiting for review~~, MERGED)
- [ ] Under [Web API Routing](https://docs.microsoft.com/en-us/aspnet/web-api/overview/web-api-routing-and-actions/) TOC section, this page needs minor update only on which version of Visual Studio used (under the **Prerequisites** heading): https://github.com/aspnet/Docs/blob/master/aspnet/web-api/overview/web-api-routing-and-actions/attribute-routing-in-web-api-2.md Related PR: #4500 (STATUS: PR submitted, waiting for review)
- [ ] Under [Web API Routing](https://docs.microsoft.com/en-us/aspnet/web-api/overview/web-api-routing-and-actions/) TOC section, this page needs update to use  VS 2017: https://github.com/aspnet/Docs/blob/master/aspnet/web-api/overview/web-api-routing-and-actions/create-a-rest-api-with-attribute-routing.md Related PR: #4500 (STATUS: PR submitted, waiting for review)
- [ ] Under Advanced Topics, Configure Web API 2 section: https://github.com/aspnet/Docs/blob/master/aspnet/web-api/overview/advanced/configuring-aspnet-web-api.md Related PR: #4500 (STATUS: PR submitted, waiting for review)

~~The list above currently is an ongoing moving list, it will always be updated as necessary.~~
**UPDATE: The list has been finalized for now on 5th October, with additional notes below.** 
There are some pages that need additional updates to support VS 2017 such as this page and its sub pages:
https://docs.microsoft.com/en-us/aspnet/web-forms/overview/deployment/visual-studio-web-deployment/
But these pages might be better to be put under one WIP on its own, because the updates will be large under Visual Studio Web Deployment section.

Please do not close this issue 🙂

**Comment by eriawan** [comment]
All of the tasks' PRs have been submitted and merged! 
Thanks @Rick-Anderson and @scottaddie for reviewing and merging them! 🙂

**Comment by scottaddie** [comment]
@eriawan Thanks again for your Herculean effort to update these docs!

**Comment by eriawan** [comment]
@scottaddie you're welcome 🙂
