### ISSUE TITLE
Lukes top 15

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4385]
- [ ] https://github.com/aspnet/Docs/issues/4033
- [ ]

**Comment by guardrex** [comment]
* [ ] 2.0 Auth updates #3777
  * [ ] **Update** [security/data-protection/compatibility/cookie-sharing](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/compatibility/cookie-sharing) #3776
  * [ ] **Update** (+rename/retitle) [security/authentication/cookie](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?tabs=aspnetcore2x)
  * [ ] **Update/Section** [security/data-protection/configuration/index](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/index) and sub-pages for new config.
    * [ ] **Topic** Add instructions for Redis -- Similar to the [KV Config Provider topic](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?tabs=aspnetcore2x)?
    * [ ] **?** Add instructions for Key Vault -- More than [KV Config Provider](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?tabs=aspnetcore2x)?
* [ ] **Topic** Razor Pages config #4281
* [ ] **Topic** Unit testing Razor Pages #4232
* [ ] 2.0 Logging updates #4093
  * [ ] **Section** `FormattedLogValues` aspnet/Logging#694
  * [ ] **Topic** `ChangeToken` #1291
  * [ ] **Topic** `LoggerMessage.DefineScope` pattern #2810
* [ ] **Topic** `IHostedStartup` #4438
* [ ] **Topic** `IStartupFilter` #1935
* [ ] **Topic** `IMiddleware` #3665

**Comment by guardrex** [comment]
@Rick-Anderson For Key Vault Config Provider ... we have it, but perhaps that whole TOC should be re-assessed and that topic moved into the DP Configuration section.

For the Redis one, you mean just a topic similar to the KV topic, correct?

**Comment by Rick-Anderson** [comment]
@guardrex  You don't need to do these in order. Start working on one that is clearly defined.   @danroth27  can you answer Luke's questions? cc / @scottaddie   

PS, I'm offline the rest of the day.

**Comment by guardrex** [comment]
I can take a look at your priority labels and sort them that way.

**Comment by danroth27** [comment]
For key vault and data protection I believe the ask from @blowdart was to document how to protect your data protection keys using key vault. We should setup some time with @blowdart to go through the details of the scenario and get them written up. @blowdart chime in if you disagree.

**Comment by guardrex** [comment]
Oh, yes! ..... I recall that now. IIRC there is an existing sample that I can put an eye on (including for Redis). @blowdart if you don't have an outline already, I can hatch one up and u can revise it from there. Might save you some time if you don't already have one.

**Comment by blowdart** [comment]
Turns out we forgot to ship it in 2.0 - which might explain the lack of docs :D

**Comment by danroth27** [comment]
Ha! Well, @guardrex I guess you're off the hook on that one then :smile:

**Comment by guardrex** [comment]
Ah. Then I must merely recall a convo about it. It should come off the list unless u would like a preview topic.
