### ISSUE TITLE
Tracking Issue for Hosting & Deployment updates

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5100]
#### Stage 1
* [x] [CSAT Host ASP.NET Core on Windows with IIS (\#4821)](https://github.com/aspnet/Docs/issues/4821)
  * Split *Troubleshooting* into its own topic.
  * **Lightly** UE pass all content. Drop "you"/"your" language, fix bad spacing, drop future tense, etc. Hold off on heavy editing until Stage 3 to facilitate getting Antares Stage 2 content up.
  * Proposal: Reorganize the TOC to organize topics by host platform.
  * Proposal: Split *Common Errors* into its own topic.
  * Proposal: Refactor *Common Errors* so that it applies to both Antares and IIS hosting scenarios.
  * Redirect file additions as needed.
* [x] [Document deploying an already running app on different OSes with different webservers (\#4866)](https://github.com/aspnet/Docs/issues/4866)
* [x] [Document reasoning for web.config location (\#5055)](https://github.com/aspnet/Docs/issues/5055) Also, specify where VS creates the file on publish.
#### Stage 2
* [x] [Publishing to Azure App Service (\#2800)](https://github.com/aspnet/Docs/issues/2800) Antares-specific publishing/hosting. This is a reference topic and meant to orient a reader to the resources they need to be successful with ASP.NET Core and Antares. We currently have four tutorial topics to nest under this in the TOC.
* [x] [Diagnose ASP.NET Core startup errors on Azure App Service (\#4890)](https://github.com/aspnet/Docs/issues/4890) Pertains to an Antares-specific troubleshooting topic.
* [x] [Diagnosing startup errors (\#4685)](https://github.com/aspnet/Docs/issues/4685) Pertains startup troubleshooting (IIS and Antares).
* [x] [Link Startup exception handling to new Antares doc (\#5159)](https://github.com/aspnet/Docs/issues/5159)
#### Stage 3
* [x] [UE pass topics in the Host and Deploy section of the TOC (\#5135)](https://github.com/aspnet/Docs/issues/5135)
* [x] Create issue to link the hosting bundle installer at dot.net downloads page to the ANCM topic. [Describing the hosting bundle installer on the .NET Downloads page \#5505](https://github.com/aspnet/Docs/issues/5505)
* [x] 3A: IIS troubleshooting https://github.com/aspnet/Docs/pull/5380
* [x] 3B: Hosting on IIS https://github.com/aspnet/Docs/pull/5394
* [x] 3C: ANCM UE pass https://github.com/aspnet/Docs/pull/5477
* [x] 3D: UE on remaining topics in host-and-deploy topics

### Proposed TOC for *Hosting and deployment*

I recommend that we reorganize the TOC to group the topics by hosting platform. It should be easier for readers to grok related resources now that we're adding new topics and have a need for a common errors topic that covers Antares and IIS.

Folder names are in parentheses. The plan is to move from "publishing" to "host-and-deploy," which matches the TOC title *Hosting and deployment*.

* **Host and deploy with ASP.NET Core** (*host-and-deploy*)
   * Host on Azure App Service (*host-and-deploy/azure-apps*) **<-- #2800**
        * Publish to Azure with Visual Studio
        * Publish to Azure with CLI tools
        * Continuous deployment to Azure with Visual Studio and Git
        * Continuous deployment to Azure with VSTS
        * Troubleshoot ASP.NET Core on Azure App Service **<-- #4890 and #4685**
   * Host on Windows with IIS (*host-and-deploy/iis*)
        * Troubleshoot ASP.NET Core on IIS **<-- Split out of the current IIS topic.**
        * ASP.NET Core Module Configuration Reference
        * Development-time IIS support in Visual Studio for ASP.NET Core
        * IIS Modules with ASP.NET Core
  * Host in a Windows service
  * Host on Linux with Nginx
  * Host on Linux with Apache
  * Host in Docker (*host-and-deploy/docker*)
     * Building Docker Images
     * Visual Studio Tools for Docker
     * Publish to a Docker Image
  * Visual Studio publish profiles
  * Directory structure
  * **Common errors reference for Azure App Service and IIS**
  * Add app features from an external assembly using IHostingStartup

### New topics

Consider that we shouldn't put "startup" in the titles of the new troubleshooting topics. These troubleshooting topics will contain content that pertains to more than just startup problems.

#### Hosting and deployment landing page

Title: Host and deploy ASP.NET Core
UID: host-and-deploy/index

#### Host on Antares topic

Title: Host ASP.NET Core on Azure App Service
UID: host-and-deploy/azure-apps/index

#### Antares troubleshooting topic

Title: Troubleshoot ASP.NET Core on Azure App Service
UID: host-and-deploy/azure-apps/troubleshoot

I'll post an outline for this for approval. I'll put it on either #4685 or #4890 in a few days. I'll ping everyone over there when it goes up.

If the proposed TOC and UID are approved, the link will be:
```
https://docs.microsoft.com/aspnet/core/host-and-deploy/azure-apps/troubleshoot
```

#### IIS troubleshooting topic

Title: Troubleshoot ASP.NET Core on IIS
UID: host-and-deploy/iis/troubleshoot

#### Common errors topic

Title: Common errors reference for Azure App Service and IIS with ASP.NET Core
UID: host-and-deploy/azure-iis-errors-reference

### Move Hosting topics

Move the hosting topics into the new *Host and deploy* TOC area. Update xrefs to these topics. Add redirects.

cc/ @Rick-Anderson @scottaddie @danroth27 @glennc @Andrew-MSFT @mlorbetske @Tratcher

**Comment by guardrex** [comment]
An alternative that doesn't nest Azure Apps and IIS so deeply has the common errors topic out at the bottom:

* **Hosting and deployment** (*host-and-deploy*)
   * Host on Azure App Service (*host-and-deploy/azure-apps*) **<-- #2800**
        * Publish to Azure with Visual Studio
        * Publish to Azure with CLI tools
        * Continuous deployment to Azure with Visual Studio and Git
        * Continuous deployment to Azure with VSTS
        * Troubleshoot ASP.NET Core on Azure App Service **<-- #4890 and #4685**
   * Host on Windows with IIS (*host-and-deploy/iis*)
        * Troubleshoot ASP.NET Core on IIS **<-- Split out of the current IIS topic.**
        * ASP.NET Core Module Configuration Reference
        * Development-time IIS support in Visual Studio for ASP.NET Core
        * IIS Modules with ASP.NET Core
  * Host in a Windows service
  * Host on Linux with Nginx
  * Host on Linux with Apache
  * Host in Docker (*host-and-deploy/docker*)
     * Building Docker Images
     * Visual Studio Tools for Docker
     * Publish to a Docker Image
  * Publish profiles in Visual Studio
  * Directory structure
  * **Common errors reference for Azure Apps and IIS**
  * Add app features from an external assembly using IHostingStartup
