### ISSUE TITLE
SignalR  for ASP.NET Core 2.1 master issue

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5389]
[Announcing SignalR (alpha) for ASP.NET Core 2.0 blog](https://blogs.msdn.microsoft.com/webdev/2017/09/14/announcing-signalr-for-asp-net-core-2-0/)

- [x]  Introduction #5390
- [x] Tutorial: Getting Started with ASP.NET Core SignalR #5391
- [x] ASP.NET Core SignalR Hubs
- [x] ASP.NET Core SignalR JavaScript Client
- [x] Supported Platforms
- [x] ASP.NET Core SignalR .NET Client
- [x] Publish ASP.NET Core SignalR app
- [ ] Intro to SignlaR Security
- [ ] Authorization & Authentication

Per `@BrennanConroy` 
https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/  would be a good start, plus the 2 blog posts we made for the Alpha releases at 
https://blogs.msdn.microsoft.com/webdev/2017/09/14/announcing-signalr-for-asp-net-core-2-0/
https://blogs.msdn.microsoft.com/webdev/2017/10/09/announcing-signalr-for-asp-net-core-alpha-2/

The first tutorial is super simple and we have a working sample of it using AspNetCore + SignalR Core at https://github.com/aspnet/SignalR-samples/tree/master/ChatSample/ChatSample

You can request review from davidfowl, BrennanConroy, anurse, and mikaelm12 when making PR’s for the docs and we’ll be glad to give our feedback.

**Comment by anurse** [comment]
I'm going to throw some notes in various comments here so we don't lose track of them:

* `@aspnet/signalr` NPM package requires NPM 5.6.0 or higher. (source: https://github.com/aspnet/SignalR/issues/1458)

**Comment by KPixel** [comment]
It would be great to have docs for the lower layers (Sockets and Protocols).
I think they will be very helpful to people who need a well designed networking library.

**Comment by anurse** [comment]
Agree completely, it's just going to be a matter of prioritization :). That layer is the core of what's brand new in SignalR, so we'll want to document it well.

**Comment by redplane** [comment]
Hi, 

Any tutorials for Signalr core 2.1 authentication & authorization ?

I'm facing with one issue in Signalr core 2.1 that I already pasted here:
 [https://stackoverflow.com/questions/49535959/authorize-doesnt-work-in-signalr-of-asp-net-core-2-1](url)

**Comment by rachelappel** [comment]
@redplane Docs for that are coming in a future sprint. I believe the one after this. We will keep this updated.

**Comment by Rick-Anderson** [comment]
Closing this master issue. We can create a SignalR project that spans multiple issues.
