### ISSUE TITLE
Sprint 133 goals 3-17 to 4-6

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5581]
@scottaddie 

- [x] Support product unit on server docs.
- [ ]  Check on versioning
- [ ] Web API conventions #5401 - Rich Swagger support without attributes (aspnet/Mvc#6870, aspnet/Mvc#6784)

@rick-anderson
- [x] Support product unit on .NET framework and  server docs. 
- [ ] Update scaffolding instructions with Feb patch release #5263

@rachelappel 

- [x]  Update intro to point to ASP.NET Framework https://github.com/aspnet/Docs/issues/5682
- [x]  Tutorial: Getting Started with ASP.NET Core SignalR #5391
- [x]  SignalR Hubs docs https://github.com/aspnet/Docs/pull/5639
- [x] Intro to SignalR #5390
- [ ] SignalR Clients https://github.com/aspnet/Docs/issues/5646
- [ ] SignalR Publish

@guardrex

- [x] Add Note About Order Mattering in Startup.Configure #5800
- [x] Docs for UseForwardedHeaders, working with reverse proxies and load balancers #2384 
- [x] Security > XSRF/CSRF updates #5554 
- [ ] Enhance content for stdout log writing #5891

**Comment by Rick-Anderson** [comment]
@guardrex  can you add your goals

**Comment by guardrex** [comment]
@Rick-Anderson Sure ... I'll set up the Blazor issues, then I'll get everything on here.

I guess you only want the repo issue goals, right? ... not the :beer: drinking goals.

... or should I open an issue for that???? :smile: lol

**Comment by rachelappel** [comment]
@guardrex I wanna see what drinking goals we have :D :beer: :beer: :beer:
