### ISSUE TITLE
Doc content for Blazor 0.2.0

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#5678]
* [ ] ASP.NET Core Blazor (landing page) #5764 @guardrex
  * [ ] Build your first Blazor app tutorial #5766 @guardrex
  * [ ] Introduction to Blazor #5765 @SteveSandersonMS (prep+PR by @guardrex)
  * [ ] Blazor components #5767 @guardrex
  * [ ] Blazor layouts #5769 @rstropek
  * [ ] Dependency injection in Blazor #5770 @rstropek
  * [ ] Host and deploy Blazor #5771 @guardrex

_From @danroth27 on March 8, 2018 23:55_

Tracking bug for adding docs for the 0.1.0 release.

_Copied from original issue: aspnet/Blazor#223_

**Comment by danroth27** [comment]
_From @guardrex on March 10, 2018 6:24_

I listed a few suggestions below. I'd be happy to assist.

Whatever direction you decide to go, I hope you'll at least permit me to submit a small PR against the README ... stomp around with my big dinosaur feet a bit and fix it up! :smile: (The Wiki FAQ could use a light pass as well. I can send you a corrected text file.)

### Description Recommendation

Consider changing the repo description to ...

> Blazor is an experimental .NET web framework using C#/Razor and HTML that runs in the browser with WebAssembly.

### Hosting Recommendation

@danroth27, you mentioned using the repo Wiki. I suggest using a separate repo and GH Pages so that PRs are possible. After all, I can't help *if I can't help.* :smile: ... nor can anyone else.

"Steal" the official docs/DocFX theme so that it brands with .NET products/docs. I'm not talking about building docs ... I'm just referring to the layout and style of the static HTML doc content. I can help (or lead) on setting it up if you like.

### Content Recommendations

#### Landing page content

Sidebar: TOC

* Define and describe Blazor (Ref: README)
* Experimental note
* Why use Blazor? (benefits and features; link to FAQ)
* List work-in-progress (link issues if possible)
* List upcoming features (link issues if possible)
* Seek to enlist the aid of the community
* Next steps: Link to *Introduction*, *FAQ*, and *Get started*

#### TOC

Use the official docs TOC structure to simplify transitioning to the official docs later if Blazor becomes a *real thing* :crossed_fingers:. For example, use folders with index pages for single content pages that will become TOC areas later, `_static` asset folders, `sample` sample folders, etc. Follow the official style and grammar guidelines. This will vastly simplify things later. It will :guitar: *ROCK!* :guitar: :+1:

I'm not suggesting that all of the following content be created immediately. I'm just proposing a general outline for the future that offers some hints on how to start.

* Introduction (Ref: [Steve's post](http://blog.stevensanderson.com/2018/02/06/blazor-intro/)).
* FAQ (Ref: Wiki FAQ)
* Get started (Ref: README): Prereqs, Build, Run tests, Run end-to-end tests, Run all tests, Build VS tooling, Use VS tooling
* Tutorials
  * Build a Blazor app with Visual Studio
  * Build a Blazor app with Visual Studio Code (possible today?)
  * Build a client-server Blazor solution with Visual Studio
  * Build client-server Blazor projects with Visual Studio Code (possible today?)
* Fundamentals
  * TBD: Subjects such as configuration, app startup, Razor concepts, functions, lifecycle (+StateHasChanged), databinding, event binding, components, render fragments, routing, app state/session (https://github.com/aspnet/Blazor/pull/205), logging, error handling, DI, more?
* Test and debug (e.g., [live reloading \#193](https://github.com/aspnet/Blazor/pull/193))
* Data access
* Security
* Performance
* Host and deploy
  * Host on the Azure CDN
  * Host on a file server
  * Host on Azure App Service or on an IIS/Linux server
    * Hosting app configuration
    * Link to the *Servers*, *Hosting*, and *Host and deploy* topics in ASP.NET Core docs
  * Directory structure (of Blazor assets)
* Common errors reference
* Release notes
* Contribute

**Comment by danroth27** [comment]
_From @rstropek on March 10, 2018 20:40_

@guardrex FYI I started a small docs project for Blazor at [https://learn-blazor.com/](https://learn-blazor.com/) (work in progress!). It should help people as long as no official documentation is available. Later, I will probably use some of the content in trainings and workshops that I will do. Feel free to reuse content and/or contribute.

Greetings,
Rainer.

**Comment by danroth27** [comment]
_From @guardrex on March 11, 2018 1:14_

@rstropek Great job! I fleshed out the *Fundamentals* list with some of your content areas.

Was your intention to maintain a parallel doc set, or were you interested in moving that content into topics in the doc set that they might establish?

Note that I don't currently have anything to do with this project. I'm a contractor working on the ASP.NET Core docs team. However, I would like to work on this doc set in my spare time. At this point, I'm just offering my services to @danroth27, @SteveSandersonMS, and the gang.

**Comment by danroth27** [comment]
_From @dragnilar on March 11, 2018 4:8_

@rstropek

Awesome site and great examples. I think this will definitely help for people who want to get started with Blazor.

**Comment by danroth27** [comment]
We've decided to go ahead and put the Blazor preview documentation on docs.microsoft.com with the ASP.NET Core docs under the [client-side development section](https://docs.microsoft.com/en-us/aspnet/core/client-side/). Moving this issue to the https://github.com/aspnet/docs repo.

The Blazor node and pages should clearly indicate that these are preview docs for an experimental framework.

@guardrex If you want to go ahead and start working on this that would be great!

**Comment by guardrex** [comment]
> If you want to go ahead and start working on this that would be great!

### :tada: Whoo hoooo! 🎈 *Thank you @danroth27!*

**Comment by scottaddie** [comment]
It's like Christmas in March! :-) Looking forward to learning more about Blazor.

**Comment by guardrex** [comment]
My birthday is right around the corner ... how did he know??!!! 🎁😀 

I created an orange "Blazor" label for the issues. That will help me, since I use the GH UI quite a bit to organize my work, and the labels are useful at-a-glance. However, let's discuss the label text, "Blazor," and the color. That's probably fine for the text. Orange isn't represented in the labels. Any other ideas on these points, @scottaddie?

**Comment by scottaddie** [comment]
@guardrex I'm fine with what you've done.

**Comment by guardrex** [comment]
@scottaddie Good times ... I'm working on getting the new topic list together for a tracking issue for my work. Blazor topics will factor into it. I'll have the tracking issue with a draft list up later today.

On this issue (Blazor docs 0.1.0), I'll add a comment to this thread based on the outline I posted earlier :point_up: for Blazor TOC tracking. Once we get that solved, I'll open issues for the individual topics and add them to my workload.

**Comment by danroth27** [comment]
@guardrex Let's get some time with @SteveSandersonMS to go over the outline and prioritize the topics.

**Comment by guardrex** [comment]
@danroth27 Sure thing. I Tweeted him a little while ago with my Aquent email. llatham ---AT--- aquent.com.

**Comment by guardrex** [comment]
Thanks @EdCharbeneau! ... We're working on the process now for getting the effort underway. Stay tuned. I'll post updates here as we go.

**Comment by guardrex** [comment]
@danroth27 @SteveSandersonMS @rowanmiller 

See the OP at the top ☝️ for the issues tracked.

**Comment by guardrex** [comment]
Tracking moved to 0.2.0 milestone of aspnet/Blazor.Docs at: https://github.com/aspnet/Blazor.Docs/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.2.0
