### ISSUE TITLE
SignalR: Tracking issue for 2.2 changes

### ISSUE THREAD

**Issue by anurse** [aspnet/Docs#6925]
Not sure the most appropriate way to do this, but this seems like a good start. We should start capturing changes we expect to be present in 2.2 so we can revisit when updating docs for the release

* Client-to-Server keep-alive (owner @anurse):
  * [x] New configuration option on `HubConnection`: `KeepAliveInterval` - How frequently the client will send keep-alive messages
  * [x] New configuration option on `HubOptions`: `ClientTimeoutInterval` - The server will consider the client disconnected if it hasn't received a message (including keep-alive) in this interval. It **is** possible for it to take longer than this timeout interval for the client to actually be marked disconnected, due to how this is implemented.
* [x] Added Java Client for ASP.NET Core SignalR with support for Azure SignalR Service [2862](https://github.com/aspnet/SignalR/issues/2862)
* [x] Added Node.JS support for the JavaScript client [2535](https://github.com/aspnet/SignalR/issues/2535)
* [x] Detect stream cancellation from client in streaming hub method [2597](https://github.com/aspnet/SignalR/issues/2597)
* [x] Added Redis v2 package  [#3077](https://github.com/aspnet/SignalR/issues/3077)

`@rick-anderson edit:` @tdykstra  to test all tutorials with 2.2 Preview3 `@tdykstra edit:` Done for JS and TS tutorials

**Comment by Rick-Anderson** [comment]
@bradygaster 	please review/update

**Comment by bradygaster** [comment]
@Rick-Anderson assigning the new-and-awesome SignalR label so we can triage these during our regular team triage.

**Comment by bradygaster** [comment]
once #10611 is merged this will be complete, so closing now.
