### ISSUE TITLE
ASP.NET Core 2.2 Master issue

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#7180]
**Last Updated: 1/4/2019**

`@danroth27`  to order these

@tdykstra 

- [x] SignalR: Java client #8256 
- [x] update Tutorial: Get started with SignalR to 2.2 #8335

@Rick-Anderson 

- [x] Update Create a Razor Pages web app to 2.2 #8334
- [x] Update Create a Web API to 2.2 #8336 
- [ ] VSC and VS for Mac, let scaffolder add DBcontext, connection string, etc #9945
- [ ] Update Introduction to Identity for 2.2 #9566

@scottaddie 

- [x] Create docs for LibMan #7246
- [x] SignalR: Configuring CORS #6078
- [x] Update Routing to 2.2 endpoint routing. #8331 
- [x] Open API Analyzers & Conventions #8332
- [x] Add documentation for Dispatcher related work #7528
- [ ] Describe new client code generation features (planned for 2.2 Preview 3) #8462
- [ ] Add documentation to support code and document generator tooling #8461

ryan brandenburg 

- [ ] Update Angular SSR docs to match updated Angular 6 template #8139

@guardrex

- [x] HTTP2 scenario coverage #7161
- [x] Remove webapp alias notice #6959
- [x] ANCM: IISExpress and switching hostingModel #5599
- [x] Update host and deploy topics for inproc #5449
- [x] ANCM in-proc hosting scenario #5403 
- [x] Brotli compression #7715 
- [x] Health Checks scenario coverage #7734
- [x] Convert UseKestrel to ConfigureKestrel #7851 
- [x] CORS explicit policy configuration #7924
- [x] Swap `ConfigureKestrel` for `UseKestrel` See: #7851 (also apply `ConfigureKestrel` API links) Work on the sample tracked by #8571.
- [x] Update Partial Views topic #8483
- [x] Installing hosting bundle seems to cause restart of application pools #8428 
- [x] Add Brotli compression to the sample app #8559
- [ ] Add API links and perform 2.2 RTM updates #8518
- [x] Update IIS Modules for in-proc hosting model #8682 
- [x] ANCM: Detect client disconnects and logging #9141
- [x] Routing topic updates #9527
- [x] Options Validation #9443
- [ ] Document Domain Routing Policies (DomainMatcherPolicy) #10151
- [ ] Document AllowRecompilingViewsOnFileChange #10108

anurse/bradygaster
- [ ] (Copiled from) SignalR: Tracking issue for 2.2 changes #6925
* Client-to-Server keep-alive (owner @anurse):
  * New configuration option on `HubConnection`: `KeepAliveInterval` - How frequently the client will send keep-alive messages
  * New configuration option on `HubOptions`: `ClientTimeout` - The server will consider the client disconnected if it hasn't received a message (including keep-alive) in this interval. It **is** possible for it to take longer than this timeout interval for the client to actually be marked disconnected, due to how this is implemented.
* Added Java Client for ASP.NET Core SignalR with support for Azure SignalR Service [2862](https://github.com/aspnet/SignalR/issues/2862)
* Added Node.JS support for the JavaScript client [2535](https://github.com/aspnet/SignalR/issues/2535)
* Detect stream cancellation from client in streaming hub method [2597](https://github.com/aspnet/SignalR/issues/2597)
* Added Redis v2 package  [#3077](https://github.com/aspnet/SignalR/issues/3077)

**PU**

- [x] Add websocket origin feature to docs #9363
- [x] [SignalR] [Java] Document minimum Android API levels #9335
- [x] Certificate requirements for HTTP/2 TLS negotiation on Windows Server 2012R2/Windows 8.1 #9210
- [ ] 2.2 Authorization Server #8789
- [ ] Document main Azure Active Directory integration scenarios in our templates #7224

**Unassigned**

- [ ] Project Bedrock transports #5521 
- [ ] YouTube version of this tutorial #9908
- [ ] No error to debug tag helper rendering #9753
- [ ] Missing documentation on requiring authentication in custom policies #9712
- [ ] YouTube version #9612
- [ ] IEnumerable<IFormFile> model binding works only from version 2.2.0-preview1 up #8797
- [ ] master issue:Update to angular 6 #8816

**Comment by Rick-Anderson** [comment]
@guardrex  I think I can close this because we can use https://github.com/aspnet/Docs/projects/21 to track all this.

**Comment by guardrex** [comment]
oh, ok. :+1:

**Comment by guardrex** [comment]
@Rick-Anderson @scottaddie @tdykstra 

I updated this today (12/29) for all issues with a **2.2** or **2.2 Update** label.

Next, I'll update the **2.2 scenarios** project.

**Comment by Rick-Anderson** [comment]
@scottaddie @tdykstra @guardrex 	
closing as we don't need this. 3.0 will soon be the focus.
