### ISSUE TITLE
RexTracker master issue

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#7523]
[All assigned open issues](https://github.com/aspnet/Docs/issues/assigned/guardrex)

#### Completed

- [x] 138: Document where ApplicationName is set #7283
- [x] 138: Integrations Tests Page Missing Prerequisite #7095
- [x] 138: Sample of custom X-Forwarded-For header name may be misleading #7515 
- [x] 138: Does IIS use ASPNETCORE_ENVIRONMENT? #6605 
- [x] 138: UE pass on Host in a Windows Service doc #5578 
- [x] 138: Components that need specific web-farm configuration #3255 
- [x] 138: Document logging configuration schema #7128
- [x] 138: DP key ring management updates #7589
- [x] 139: Hosting startup topic updates #7678 
- [x] 139: Mock service injection for integration tests topic #7511
- [x] 139: How those app share cookies? #7392
- [x] 139: Enhance DP cert protect/unprotect keys coverage #7358
- [x] 139: Configuration coverage #7102 
- [x] 139: Dependency injection with convenience methods #6783
- [x] 139: Document overriding app settings in Azure Portal #6514
- [x] 139: Enforcing SSL topic: HTTPS_PORT env var details #7767
- [x] 140: Persist addl claims+tokens w/ext providers #8310 
- [x] 140: Apply Core and netfx framework naming consistently across the repo #7455 
- [x] 141: ConfigureKestrel updates #8384
- [x] 141: Partial View from a Razor Page method #8188
- [x] 141: CORS explicit policy configuration #7924
- [x] 140: Test controllers topic+sample updates #8232 
- [x] 141: HTTP2 scenario coverage #7161
- [x] 141: Update razor-pages-convention-features.md #6173
- [x] 141: Additional content on Cookie Policy Middleware #8382 
- [x] 141: Brotli compression #7715 
- [x] 141: Hosting bundle causes restart of application pools #8428 

#### In progress and review

- [ ] 142: Update host and deploy topics for inproc #5449 :bell: **IN REVIEW**
- [ ] 142: ANCM in-proc hosting scenario #5403 :bell: **IN REVIEW**
- [ ] 142: ANCM: IISExpress and switching hostingModel #5599 :bell: **IN REVIEW**

#### Long-term issues

The following issues require work that will post-date Sept. 25:

* Q3: Sample Update Tracking Issue #5495 🏃 **IN PROGRESS**
* Q3: Update to CreateWebHostBuilder - MD files #6091 🏃 **IN PROGRESS**
* Q3: Replace M.A.All meta-package to M.A.App - MD files #5314 🏃 **IN PROGRESS**
