### ISSUE TITLE
Improve docs around areas + pages + identity UI + URL generation

### ISSUE THREAD

**Issue by rynowak** [aspnet/Docs#8291]
Our docs don't currently explain how areas + pages + URL generation works. Users will likely run into this when customizing the identity UI - which is in an area by default.

For instance in https://github.com/aspnet/Mvc/issues/8280 - the user copy-pasted some link generation code from the identity UI into a non-area-based page and wasn't sure why it didn't work. 

It looks like the following things could be cleaned up:
- Razor pages docs don't mention areas https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-2.1
- Areas docs don't mention Razor Pages https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-2.1#link-generation
- I'm not sure we have docs for identity UI 🤷‍♂️

**Comment by Rick-Anderson** [comment]
- [ ] #8309 Add link to areas in RP doc
- [ ] new doc: Razor Pages Areas #5407
- [ ] Add links or short section on Identity 2.1 exposes endpoints with the Identity area. #8311

**Comment by Rick-Anderson** [comment]
Fixed in #11290 and #11199
